### PR TITLE
修复并发上传时程序崩溃的问题

### PR DESCRIPTION
**Pull request by fengyoulin**
FIX：原有代码中多个线程使用同一个lua_State造成问题，现为每个线程分配lua_State并存储于TLS中。

### CODE REVIEW

**Comment by buaazp** [comment]
怒赞！之前确实有好几个报崩溃疑似跟lua有关，一直也没查到原因。你这个有没有能稳定复现crash的case，分享一下我好校验。

**Comment by fengyoulin** [comment]
这个是我复现时用来压力测试的Go代码，如果把zimg log level开到7，应该很容易复现，6的话可能要多试两次。
`package main

import (
	"bytes"
	"fmt"
	"net/http"
	"strings"
	"sync"
	"time"
)

var count int = 0
var lock sync.Mutex

func post(index int) {
	image1 := []byte{
		0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52,
		0x00, 0x00, 0x00, 0x24, 0x00, 0x00, 0x00, 0x24, 0x08, 0x06, 0x00, 0x00, 0x00, 0xE1, 0x00, 0x98,
		0x98, 0x00, 0x00, 0x05, 0x6D, 0x49, 0x44, 0x41, 0x54, 0x78, 0xDA, 0xCD, 0x58, 0x5B, 0x48, 0x1D,
		0x57, 0x14, 0xDD, 0xF7, 0xFA, 0x4A, 0x63, 0xAB, 0x1F, 0x4A, 0x10, 0x03, 0x05, 0x91, 0xA2, 0xD2,
		0x20, 0x8A, 0xB1, 0x95, 0xD2, 0x87, 0xFA, 0x61, 0xA2, 0x0D, 0x88, 0x52, 0xB5, 0x45, 0x51, 0xEA,
		0x47, 0x29, 0xF4, 0xCB, 0x47, 0xFA, 0xF8, 0xD0, 0x8F, 0xE4, 0xA3, 0x4D, 0x7D, 0xE4, 0xAB, 0x50,
		0xFA, 0x61, 0x89, 0x44, 0x5A, 0xB5, 0x44, 0x04, 0xEB, 0xEB, 0x43, 0xED, 0x83, 0x60, 0xAB, 0xA2,
		0x88, 0x45, 0xA5, 0x88, 0x50, 0x50, 0x44, 0xF4, 0x43, 0x5B, 0x5B, 0xDF, 0x76, 0xAF, 0x93, 0xB3,
		0xA7, 0xE7, 0x4E, 0x66, 0xE6, 0xDE, 0x84, 0x96, 0x74, 0xC3, 0x62, 0xEE, 0xCC, 0x3D, 0x73, 0xCE,
		0x9A, 0xB5, 0xD7, 0x3E, 0xE7, 0xCC, 0xF8, 0x28, 0xF4, 0xF0, 0x31, 0xFC, 0x8C, 0x93, 0x47, 0xB8,
		0x07, 0x11, 0xC6, 0x38, 0x65, 0x9C, 0x85, 0x3A, 0x48, 0x28, 0xE1, 0xD7, 0x9D, 0x22, 0x9E, 0x66,
		0x64, 0x31, 0x5E, 0x60, 0x64, 0x30, 0x9E, 0x65, 0x3C, 0xA3, 0xFF, 0xFB, 0x9D, 0xF1, 0x1B, 0x63,
		0x8E, 0xF1, 0x33, 0x63, 0x86, 0xF1, 0x87, 0x43, 0x1F, 0x8F, 0x4D, 0xC8, 0xEC, 0x24, 0x89, 0xF1,
		0x2E, 0xE3, 0x75, 0xC6, 0xF3, 0x21, 0x3E, 0xC8, 0x2F, 0x8C, 0x6F, 0x19, 0x9F, 0x33, 0x56, 0x43,
		0x21, 0xE6, 0x45, 0x48, 0x6E, 0x8C, 0x65, 0x7C, 0xC0, 0x78, 0x8F, 0x11, 0xA3, 0xFF, 0x0B, 0x25,
		0x05, 0x92, 0x62, 0xC4, 0x2E, 0xE3, 0x33, 0xC6, 0x2D, 0xC6, 0x8E, 0x17, 0x29, 0x37, 0x42, 0xC8,
		0x3B, 0xBC, 0xF2, 0x22, 0xE3, 0x0B, 0x46, 0xBA, 0xBE, 0x7E, 0xA4, 0x3B, 0xF3, 0xEB, 0x7B, 0xCF,
		0x6C, 0xFD, 0x98, 0xE7, 0x67, 0x7A, 0x50, 0x20, 0x42, 0x5F, 0x9F, 0x67, 0xBC, 0xC3, 0xF8, 0xC9,
		0x18, 0x23, 0x28, 0x21, 0x69, 0x58, 0xCE, 0xF8, 0x92, 0x71, 0x9E, 0x71, 0xAC, 0xAF, 0xFB, 0xC2,
		0xC2, 0xC2, 0xCE, 0x7C, 0x1C, 0x41, 0x93, 0x05, 0x46, 0x1C, 0x27, 0x27, 0x27, 0x42, 0x0E, 0x7D,
		0x86, 0x33, 0xFE, 0x64, 0xBC, 0xCD, 0xE8, 0x71, 0x22, 0x65, 0xEF, 0x58, 0xA4, 0x7C, 0x83, 0xF1,
		0xB5, 0xBE, 0x41, 0xC8, 0x04, 0x53, 0xD5, 0x95, 0x97, 0xF1, 0x5B, 0x48, 0xE1, 0xF8, 0x26, 0xE3,
		0x1B, 0xB2, 0xA5, 0xCF, 0xEC, 0x5C, 0x9E, 0x24, 0x9B, 0x31, 0xC1, 0x78, 0x4A, 0x37, 0x04, 0x19,
		0xA5, 0x0A, 0x3F, 0x30, 0xD5, 0xD4, 0xD4, 0x50, 0x5E, 0x5E, 0x1E, 0xED, 0xED, 0xED, 0x11, 0xAB,
		0xE5, 0xC8, 0x80, 0x55, 0xA1, 0xE8, 0xE8, 0x68, 0x1A, 0x1F, 0x1F, 0xA7, 0x3B, 0x77, 0xEE, 0x10,
		0x04, 0x85, 0x5A, 0x7A, 0x8C, 0x13, 0x4D, 0xE2, 0x2F, 0x46, 0x2E, 0x63, 0xCA, 0x18, 0xFB, 0x21,
		0x42, 0x30, 0xF0, 0x7D, 0x46, 0x9A, 0x56, 0x26, 0x5C, 0x37, 0x54, 0xED, 0x62, 0x63, 0x63, 0x69,
		0x69, 0x69, 0x89, 0x12, 0x12, 0x12, 0x42, 0x92, 0x66, 0x63, 0x63, 0x83, 0x52, 0x53, 0x53, 0x69,
		0x67, 0x67, 0xC7, 0x54, 0xCB, 0x67, 0xF4, 0xBD, 0xC8, 0x78, 0x89, 0x1E, 0x18, 0x3D, 0x80, 0x90,
		0x30, 0xFC, 0x98, 0xF1, 0xA1, 0x2D, 0x4D, 0x3E, 0xBF, 0xDF, 0x4F, 0xA7, 0xA7, 0xA7, 0x54, 0x5E,
		0x5E, 0x4E, 0xDD, 0xDD, 0xDD, 0x74, 0x78, 0x78, 0x48, 0xB8, 0xE6, 0x15, 0x68, 0x1F, 0x19, 0x19,
		0x49, 0x15, 0x15, 0x15, 0xD4, 0xD3, 0xD3, 0x43, 0xD2, 0x87, 0x91, 0x42, 0x49, 0xDF, 0x27, 0x8C,
		0x8F, 0x84, 0x83, 0xCF, 0x20, 0x83, 0x79, 0x06, 0x55, 0x70, 0x5E, 0xDF, 0x60, 0x8D, 0xA8, 0x25,
		0xA7, 0xC1, 0xC1, 0x41, 0xBA, 0x7A, 0xF5, 0xAA, 0x4A, 0x89, 0xA4, 0x0B, 0xD7, 0x71, 0x8E, 0xC0,
		0x35, 0xF1, 0xBB, 0xB4, 0x19, 0x1E, 0x1E, 0xA6, 0xA2, 0xA2, 0x22, 0xAB, 0x0F, 0x93, 0xB3, 0x3E,
		0xC2, 0xE4, 0xA8, 0xE2, 0x55, 0x35, 0x94, 0x61, 0x2A, 0x30, 0xC5, 0x7C, 0x83, 0xD2, 0x8E, 0x10,
		0x79, 0xA5, 0xA3, 0x94, 0x94, 0x14, 0x9A, 0x9E, 0x9E, 0x56, 0xDE, 0xC0, 0x39, 0x9E, 0x18, 0x47,
		0x7B, 0xC1, 0xC9, 0x35, 0xA8, 0x81, 0x23, 0xBC, 0x76, 0xF9, 0xF2, 0x65, 0x5A, 0x5E, 0x5E, 0x36,
		0x49, 0x49, 0xEA, 0x64, 0xAC, 0x5B, 0x3A, 0x33, 0x7E, 0xE9, 0x2D, 0x46, 0x9B, 0xEB, 0x39, 0x2D,
		0x65, 0x98, 0xA4, 0x13, 0x4F, 0x89, 0xA7, 0x6D, 0x6A, 0x6A, 0xA2, 0x1B, 0x37, 0x6E, 0xD0, 0xD1,
		0xD1, 0x11, 0x85, 0x87, 0x87, 0x5B, 0xA4, 0x66, 0x66, 0x66, 0x54, 0x4A, 0x10, 0x48, 0x69, 0x56,
		0x56, 0x96, 0x45, 0xE6, 0xF8, 0xF8, 0x98, 0x22, 0x22, 0x22, 0xA8, 0xB9, 0xB9, 0x99, 0x6E, 0xDE,
		0xBC, 0x69, 0xF5, 0x65, 0xF8, 0x49, 0xC6, 0xFA, 0x55, 0x17, 0xD3, 0xAE, 0x10, 0x7A, 0x95, 0xF1,
		0x9D, 0x56, 0x4A, 0xD2, 0x68, 0xA5, 0x0B, 0x5E, 0x98, 0x9B, 0x9B, 0x53, 0x2A, 0x69, 0x1F, 0xA8,
		0xCE, 0xBB, 0xBA, 0xBA, 0xA8, 0xB6, 0xB6, 0x56, 0x79, 0x0A, 0x81, 0x76, 0x1D, 0x1D, 0x1D, 0x54,
		0x59, 0x59, 0x69, 0x0D, 0x0C, 0xD2, 0x50, 0x27, 0x23, 0x23, 0x43, 0xB5, 0xB3, 0xA5, 0xED, 0x4C,
		0x03, 0x59, 0x7A, 0x8D, 0xF1, 0xBD, 0x0C, 0xFC, 0xBE, 0x4E, 0x59, 0x80, 0x3A, 0x62, 0xC4, 0x2B,
		0x57, 0xAE, 0xD0, 0xD0, 0xD0, 0x90, 0xEA, 0x4C, 0x94, 0xD9, 0xDC, 0xDC, 0xA4, 0xF4, 0xF4, 0x74,
		0x75, 0x84, 0x0A, 0x08, 0xA8, 0x77, 0xE1, 0xC2, 0x05, 0x9A, 0x9F, 0x9F, 0x57, 0x47, 0x51, 0x0A,
		0x28, 0x2C, 0x2C, 0xA4, 0x91, 0x91, 0x11, 0xD3, 0xDC, 0x76, 0x95, 0x90, 0xB2, 0x4F, 0x85, 0x50,
		0x17, 0xE3, 0x2D, 0xFA, 0x67, 0xDE, 0x09, 0x30, 0x33, 0xE6, 0x92, 0xEA, 0xEA, 0x6A, 0x35, 0x20,
		0xAE, 0x21, 0x65, 0xA3, 0xA3, 0xA3, 0x8A, 0xA8, 0x53, 0x60, 0xE0, 0x82, 0x82, 0x02, 0x95, 0x32,
		0xDC, 0x0F, 0xC2, 0x9D, 0x9D, 0x9D, 0x6A, 0x0E, 0x73, 0x30, 0xB7, 0xCC, 0x4B, 0x5F, 0x31, 0x2A,
		0x85, 0xD0, 0x0F, 0x8C, 0x97, 0x8D, 0x72, 0xB7, 0xCC, 0x9C, 0x94, 0x94, 0x44, 0xB3, 0xB3, 0xB3,
		0x14, 0x13, 0x13, 0x63, 0x55, 0x0F, 0x08, 0xC1, 0x3B, 0xD9, 0xD9, 0xD9, 0x01, 0x03, 0xC8, 0xEF,
		0xA9, 0xA9, 0x29, 0xE5, 0x25, 0x10, 0x92, 0x6A, 0xDC, 0xDD, 0xDD, 0xA5, 0xCC, 0xCC, 0x4C, 0x5A,
		0x5D, 0x5D, 0xB5, 0x9B, 0x5B, 0xCA, 0xFF, 0x47, 0xC6, 0x2B, 0x42, 0x68, 0x96, 0x1E, 0xEC, 0x6D,
		0x44, 0x3E, 0x4B, 0xDA, 0xDC, 0xDC, 0x5C, 0x1A, 0x1B, 0x1B, 0x0B, 0xA8, 0x20, 0x1C, 0xF1, 0x5F,
		0x49, 0x49, 0x09, 0x0D, 0x0C, 0x0C, 0x04, 0xA8, 0x73, 0xED, 0xDA, 0x35, 0xEA, 0xEB, 0xEB, 0x53,
		0xF7, 0x4B, 0x5B, 0xA9, 0xC4, 0xFC, 0xFC, 0x7C, 0x9A, 0x98, 0x98, 0xB0, 0xA7, 0x4D, 0xC6, 0xC4,
		0x1E, 0x2A, 0xD3, 0x95, 0x90, 0x19, 0x55, 0x55, 0x55, 0xCA, 0xAC, 0xE8, 0x58, 0x26, 0x44, 0xFC,
		0xDE, 0xDA, 0xDA, 0xA2, 0xEB, 0xD7, 0xAF, 0x07, 0x54, 0x59, 0x4B, 0x4B, 0x0B, 0xC5, 0xC7, 0xC7,
		0x5B, 0xAA, 0x61, 0x60, 0xFC, 0x86, 0xF9, 0xEF, 0xDE, 0xBD, 0xEB, 0x94, 0x61, 0x47, 0x42, 0x0F,
		0xA5, 0x4C, 0x5A, 0xCB, 0xD3, 0x34, 0x34, 0x34, 0x50, 0x6B, 0x6B, 0x6B, 0x40, 0x1A, 0xC4, 0xE0,
		0x65, 0x65, 0x65, 0xEA, 0xBC, 0xB7, 0xB7, 0xD7, 0x32, 0xB2, 0x99, 0xDE, 0xC6, 0xC6, 0x46, 0x6A,
		0x6B, 0x6B, 0xB3, 0x2B, 0xE3, 0x99, 0x32, 0x47, 0x53, 0x4B, 0xC8, 0xFC, 0x01, 0x25, 0x30, 0xB8,
		0xCC, 0xC2, 0xFB, 0xFB, 0xFB, 0xAA, 0xD4, 0x61, 0x56, 0x04, 0xCC, 0x8F, 0xD2, 0x3E, 0x77, 0xEE,
		0x9C, 0xD5, 0x06, 0x24, 0xA1, 0x9C, 0x6D, 0x0E, 0x0A, 0x6A, 0x6A, 0xC7, 0xB2, 0xB7, 0x57, 0x5B,
		0x62, 0x62, 0xA2, 0x32, 0x33, 0x4A, 0x5A, 0x96, 0x0C, 0x54, 0x10, 0x52, 0x8A, 0x40, 0x4A, 0x50,
		0x89, 0xB2, 0x84, 0x60, 0x4A, 0x80, 0xB9, 0xD7, 0xD7, 0xD7, 0x9D, 0xAA, 0xCB, 0x54, 0xE8, 0xA1,
		0xB2, 0x77, 0x9D, 0x18, 0xED, 0xA9, 0xAB, 0xAB, 0xAB, 0xA3, 0xF6, 0xF6, 0x76, 0x45, 0x06, 0x80,
		0x42, 0x26, 0x21, 0x28, 0x04, 0x42, 0x40, 0x7D, 0x7D, 0x3D, 0xDD, 0xBE, 0x7D, 0xDB, 0x29, 0x55,
		0x26, 0x21, 0xC7, 0x89, 0xD1, 0x75, 0xE9, 0xB0, 0x07, 0xD6, 0x32, 0xCC, 0xDA, 0xC9, 0xC9, 0xC9,
		0x6A, 0xF0, 0xA8, 0xA8, 0xA8, 0x00, 0x42, 0x07, 0x07, 0x07, 0x8A, 0xE4, 0xCA, 0xCA, 0x8A, 0x9A,
		0x9D, 0xB1, 0x96, 0xB9, 0x84, 0xEB, 0xD2, 0xE1, 0xB9, 0xB8, 0x7A, 0xA9, 0x04, 0x0F, 0xC1, 0x2F,
		0x26, 0x21, 0xB9, 0x16, 0x44, 0x1D, 0xCF, 0xC5, 0x35, 0xE8, 0xF6, 0xC3, 0x1E, 0xD8, 0xA0, 0x2D,
		0x2E, 0x2E, 0xAA, 0x0D, 0x1B, 0xBC, 0x81, 0xB5, 0x0B, 0x81, 0xB5, 0x0D, 0x3E, 0xC1, 0x86, 0x2C,
		0x2D, 0x2D, 0x4D, 0x6D, 0xD0, 0x3C, 0xC2, 0x75, 0xFB, 0x41, 0x14, 0x64, 0x83, 0x66, 0xF6, 0x62,
		0x5F, 0x4E, 0x10, 0xA6, 0x42, 0x08, 0x8F, 0x65, 0x42, 0xD4, 0x21, 0xF2, 0xD8, 0xA0, 0x91, 0x31,
		0xB0, 0xE7, 0x16, 0xD6, 0x4C, 0x5B, 0x71, 0x71, 0x31, 0xDD, 0xBB, 0x77, 0x4F, 0x9D, 0x9B, 0x0A,
		0xE1, 0xBF, 0xD2, 0xD2, 0x52, 0xEA, 0xEF, 0xEF, 0x77, 0x9B, 0x77, 0x42, 0xDA, 0xC2, 0x9A, 0x2A,
		0x39, 0x6E, 0xF2, 0xED, 0x4A, 0xC5, 0xC5, 0xC5, 0xA9, 0x0D, 0xDB, 0xC5, 0x8B, 0x17, 0x03, 0x14,
		0x5A, 0x5B, 0x5B, 0x53, 0x1B, 0xB2, 0xED, 0xED, 0x6D, 0x37, 0xDF, 0x84, 0xBC, 0xC9, 0x17, 0xDF,
		0x04, 0x7D, 0x0D, 0x92, 0x54, 0x60, 0x4B, 0x82, 0x2D, 0xAD, 0x39, 0x31, 0x62, 0xCB, 0x8A, 0xAD,
		0x86, 0x6D, 0x01, 0x95, 0x78, 0xA4, 0xD7, 0x20, 0x09, 0xCF, 0x17, 0x45, 0x53, 0xAD, 0x4B, 0x97,
		0x2E, 0x29, 0xF3, 0x4E, 0x4E, 0x4E, 0xAA, 0x1B, 0x73, 0x72, 0x72, 0x94, 0xD9, 0x17, 0x16, 0x16,
		0xEC, 0xAA, 0x3C, 0xF6, 0x8B, 0xA2, 0x9D, 0xD4, 0xFF, 0xE2, 0x55, 0xDA, 0x9E, 0x3E, 0xD7, 0x8F,
		0x0D, 0x30, 0x2D, 0x60, 0xBE, 0x75, 0xC0, 0xC4, 0xDA, 0xC8, 0xFF, 0xEA, 0xC7, 0x06, 0x3B, 0x29,
		0xC4, 0x13, 0xFF, 0x1C, 0xE3, 0x46, 0xEC, 0x89, 0x7E, 0xB0, 0xB2, 0xB7, 0xFD, 0xCF, 0x3F, 0xE9,
		0xFD, 0x0D, 0xD1, 0xA3, 0x0D, 0x58, 0xDD, 0x5C, 0x6E, 0xAB, 0x00, 0x00, 0x00, 0x00, 0x49, 0x45,
		0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82}
	image2 := []byte{
		0x89, 0x50, 0x4E, 0x47, 0x0D, 0x0A, 0x1A, 0x0A, 0x00, 0x00, 0x00, 0x0D, 0x49, 0x48, 0x44, 0x52,
		0x00, 0x00, 0x00, 0x1E, 0x00, 0x00, 0x00, 0x1E, 0x08, 0x06, 0x00, 0x00, 0x00, 0x3B, 0x30, 0xAE,
		0xA2, 0x00, 0x00, 0x01, 0x60, 0x49, 0x44, 0x41, 0x54, 0x78, 0xDA, 0x63, 0x64, 0x18, 0x20, 0xC0,
		0x38, 0x6A, 0x31, 0x36, 0x90, 0x95, 0x93, 0xF3, 0x1F, 0x44, 0x4F, 0x9B, 0x32, 0x85, 0x6A, 0x0E,
		0x25, 0x68, 0x10, 0xC8, 0xD2, 0x59, 0xB3, 0x67, 0x83, 0xD9, 0x69, 0xA9, 0xA9, 0x54, 0xB3, 0x1C,
		0xAF, 0x21, 0xC8, 0x96, 0xC2, 0x40, 0x69, 0x49, 0x09, 0x9C, 0xDD, 0xDE, 0xDA, 0x4A, 0xB6, 0x23,
		0x70, 0x6A, 0xC4, 0x66, 0x29, 0x08, 0xB0, 0xB3, 0xB3, 0x33, 0x48, 0x88, 0x8B, 0x33, 0xB0, 0xB0,
		0xB0, 0x30, 0x04, 0x05, 0x05, 0x91, 0x6D, 0x39, 0x56, 0x4D, 0xF8, 0x2C, 0x15, 0x11, 0x11, 0x61,
		0x38, 0x72, 0xE8, 0x10, 0x98, 0xEF, 0xE2, 0xEA, 0x4A, 0xB6, 0xE5, 0x18, 0x1A, 0x88, 0xB1, 0x54,
		0x46, 0x5A, 0x1A, 0x2C, 0xF6, 0xE4, 0xE9, 0x53, 0xB2, 0x2D, 0x47, 0x51, 0x4C, 0x8A, 0xA5, 0x30,
		0x40, 0xAE, 0xE5, 0x28, 0x0A, 0x2B, 0xAB, 0xAB, 0xFF, 0x77, 0xF7, 0xF4, 0x10, 0x6D, 0x29, 0x25,
		0x96, 0xE3, 0x0D, 0x6A, 0x62, 0x2C, 0x25, 0xD7, 0x72, 0x9C, 0x89, 0x6B, 0xE1, 0xA2, 0x45, 0x0C,
		0xFC, 0xFC, 0xFC, 0x0C, 0x27, 0x8F, 0x1F, 0x27, 0x68, 0x29, 0xBA, 0xE5, 0x01, 0x01, 0x01, 0x0C,
		0x9D, 0xED, 0xED, 0x78, 0x2D, 0xC7, 0x2A, 0x59, 0x51, 0x55, 0xF5, 0x7F, 0xC9, 0xD2, 0xA5, 0x0C,
		0x9F, 0x3E, 0x7D, 0x62, 0x58, 0x02, 0x74, 0x80, 0xAF, 0x8F, 0x0F, 0x51, 0x16, 0x23, 0x5B, 0xEE,
		0xE2, 0xEC, 0xCC, 0x30, 0x15, 0x4F, 0x61, 0x83, 0x55, 0x22, 0x1B, 0xE8, 0xE3, 0x3D, 0x7B, 0xF7,
		0x32, 0x54, 0x94, 0x97, 0x33, 0x14, 0x14, 0x15, 0x31, 0x2C, 0x5E, 0xB8, 0x90, 0xEA, 0x96, 0xE3,
		0x74, 0x11, 0xAD, 0x2D, 0xC7, 0x1B, 0x0F, 0xB4, 0xB4, 0x9C, 0x60, 0xEA, 0xA3, 0x95, 0xE5, 0x44,
		0xE5, 0x39, 0x4A, 0x2C, 0xA7, 0xC8, 0x62, 0x72, 0x2D, 0xA7, 0x28, 0xA8, 0xC9, 0xB5, 0x9C, 0xA2,
		0xC4, 0x85, 0x0D, 0xE4, 0xE6, 0xE5, 0xFD, 0xDF, 0xB5, 0x7B, 0x37, 0x5E, 0xCB, 0x29, 0xCA, 0x4E,
		0xF8, 0x00, 0xA8, 0x4C, 0x5F, 0xB7, 0x6E, 0x1D, 0x56, 0xCB, 0x29, 0x2A, 0x40, 0xC8, 0xB5, 0xDC,
		0xD0, 0xD0, 0x90, 0x28, 0x4B, 0x29, 0xB2, 0x18, 0xDD, 0xF2, 0xFC, 0xC2, 0x42, 0x06, 0x61, 0x21,
		0x21, 0x06, 0x2F, 0x4F, 0x4F, 0x82, 0x96, 0x52, 0x6C, 0x31, 0xB2, 0xE5, 0xBF, 0x7E, 0xFD, 0x22,
		0xDA, 0x52, 0xAA, 0x58, 0x0C, 0xB3, 0xFC, 0xD3, 0xC7, 0x8F, 0x44, 0x5B, 0x4A, 0x35, 0x8B, 0xC9,
		0x01, 0x23, 0xCF, 0x62, 0x00, 0x78, 0x04, 0x2C, 0x2E, 0xD8, 0x80, 0x5F, 0xD5, 0x00, 0x00, 0x00,
		0x00, 0x49, 0x45, 0x4E, 0x44, 0xAE, 0x42, 0x60, 0x82}
	var buffer *bytes.Buffer
	var size string
	if (index & 1) > 0 {
		buffer = bytes.NewBuffer(image1)
		size = "1446"
	} else {
		buffer = bytes.NewBuffer(image2)
		size = "409"
	}
	req, err := http.NewRequest("POST", "http://192.168.1.200:4869/upload", buffer)
	if err != nil {
		fmt.Println(err)
		lock.Lock()
		count++
		lock.Unlock()
		return
	}
	req.Header.Add("Content-Type", "png")
	req.Header.Add("Content-Length", size)
	var client http.Client
	resp, err := client.Do(req)
	if err != nil {
		lock.Lock()
		count++
		lock.Unlock()
		return
	}
	defer resp.Body.Close()
	length := int(resp.ContentLength)
	if length > 1024 {
		fmt.Println("Content too long")
		lock.Lock()
		count++
		lock.Unlock()
		return
	}
	data := make([]byte, length)
	offset := 0
	for offset < length {
		read, err := resp.Body.Read(data[offset:])
		if err != nil {
			if !strings.Contains(err.Error(), "EOF") {
				fmt.Println(err)
				lock.Lock()
				count++
				lock.Unlock()
				return
			}
		}
		offset += read
	}
	fmt.Println(fmt.Sprintf("%d: %s", index, string(data)))
	lock.Lock()
	count++
	lock.Unlock()
}

func main() {
	for idx := 0; idx < 100000; idx++ {
		go post(idx)
	}
	last1 := 0
	last2 := 0
	for count < 100000 {
		time.Sleep(time.Second)
		last1 = count
		if last2 != last1 {
			fmt.Println(fmt.Sprintf("%d finished.", count))
			last2 = last1
		}
	}
	fmt.Println("All HTTP POST finished!")
}
`

**Comment by buaazp** [comment]
测试过了，确实能复现，再次感谢！

**Comment by shidenggui** [comment]
终于修复了，我们半年前一直搞不定，最后用阿里云的oss了，撒花

**Pull request merged**
